#------
# VM 99
version: "3.9"
services:
#------
# VM 00
  reverse_proxy:
    ports:
      - 80:80
      - 443:443
      - 10050:444
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    build: ./reverse_proxy
    networks:
        ext_net:
            ipv4_address: 10.0.1.5
        int_net:
            ipv4_address: 10.0.0.5
#------
# VM 01
  core:
    build: ./core
    ports:
      - 10100:443
      #EXPOSETHIS
    environment:
        SERVICE_NAME: "core"
        CA_CERT_PASSWD: "ohpe3yoo3Oap5dohsahya1eeBieweehohseitaet"
        JWT_SECRET: "Ohtheisoashuxoolae6oocaiseepeTheiweeGhahFe8eith8eoqu0quu8cue"
        BACKUP_PASSWD: "paikoothenahKoodohfaizu9Yei0XaiN7zeiM5ga"
        MYSQL_USER: "root2"
        MYSQL_PASS: "chiMi8axaitheivoo3oh"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
        ADMIN_STATS_TOKEN: "uoVei2phooZ3ateevahf"
    volumes:
      - ./core/data:/data
    networks:
        int_net:
            ipv4_address: 10.0.0.10
    depends_on:
      - "mysql"
#------
# VM 02
  web:
    build: ./web
    ports:
      - 10200:443
      #EXPOSETHIS
    environment:
        SERVICE_NAME: "web"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
        MYSQL_USER: "root2"
        MYSQL_PASS: "chiMi8axaitheivoo3oh"

    networks:
        int_net:
            ipv4_address: 10.0.0.20
#------
# VM 03
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
      - 10300:3306
      #EXPOSETHIS
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
     - ./mysql/data:/var/lib/mysql
    networks:
        int_net:
            ipv4_address: 10.0.0.30
#+++            
  mysql_store:
    build: ./mysql_store
    ports:
      #EXPOSETHIS
      - 10301:443
    environment:
        SERVICE_NAME: "mysql"
        BACKUP_PASSWD: "Eibei0ceigaibeePheiPuwaiJ9aikoh4aem2eiYe"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
        MYSQL_USER: "root2"
        MYSQL_PASS: "chiMi8axaitheivoo3oh"
    networks:
        int_net:
            ipv4_address: 10.0.0.31
#------
# VM 04
  logging_store:
    build: ./logging_store
    ports:
      #EXPOSETHIS
      - 10400:443
    environment:
        SERVICE_NAME: "log"
        BACKUP_PASSWD: "eeQua5yiec9xee1Shoveihukoihooze6oa3caQuo"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_rsyslog/logs:/data:ro
    networks:
        int_net:
            ipv4_address: 10.0.0.40
#+++
  logging_rsyslog:
    build: ./logging_rsyslog
    ports:
      - 10402:443
      - 514:514
      - 1601:1601
    environment:
        SERVICE_NAME: "log_rsyslog"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_rsyslog/logs:/logs
      - ./logging_rsyslog/work:/work
      - ./logging_rsyslog/config:/config
    networks:
        int_net:
            ipv4_address: 10.0.0.42
#+++
  logging_view:
    build: ./logging_view
    ports:
      #EXPOSETHIS
      - 10410:443
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_rsyslog/logs:/logs:ro
    networks:
        int_net:
            ipv4_address: 10.0.0.41
#------
# VM 05
  backup:
    build: ./backup
    ports:
      #EXPOSETHIS
      - 10500:443
    environment:
        SERVICE_NAME: "backup"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./backup/data:/data
    networks:
        int_net:
            ipv4_address: 10.0.0.50    
#------
# VM 99
# network config      
networks:
    int_net:
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
    ext_net:
        ipam:
            driver: default
            config:
                - subnet: 10.0.1.5/24
