version: "3.9"

services:
  reverse_proxy:
    ports:
      - 80:80
      - 443:443
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    build: ./reverse_proxy
    networks:
        int_net:
            ipv4_address: 10.0.0.5

  core:
    build: ./core
    ports:
      - 10100:443
    environment:
        SERVICE_NAME: "core"
        CA_CERT_PASSWD: "ohpe3yoo3Oap5dohsahya1eeBieweehohseitaet"
        JWT_SECRET: "Ohtheisoashuxoolae6oocaiseepeTheiweeGhahFe8eith8eoqu0quu8cue"
        BACKUP_PASSWD: "paikoothenahKoodohfaizu9Yei0XaiN7zeiM5ga"
        MYSQL_USER: "root2"
        MYSQL_PASS: "chiMi8axaitheivoo3oh"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./core/data:/data
    networks:
        int_net:
            ipv4_address: 10.0.0.10


  web:
    build: ./web
    ports:
      - 10200:443
    environment:
        SERVICE_NAME: "web"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
        MYSQL_USER: "root2"
        MYSQL_PASS: "chiMi8axaitheivoo3oh"

    networks:
        int_net:
            ipv4_address: 10.0.0.20

  mysql:
    build: ./mysql
    ports:
      - 10300:3306
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    networks:
        int_net:
            ipv4_address: 10.0.0.30

  logging_store:
    build: ./logging_store
    ports:
      - 10400:443
    environment:
        SERVICE_NAME: "log"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_store/data:/data
    networks:
        int_net:
            ipv4_address: 10.0.0.40

  logging_rsyslog:
    build: ./logging_rsyslog
    ports:
      - 10402:443
      - 514:514
      - 1601:1601
    environment:
        SERVICE_NAME: "log_rsyslog"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_rsyslog/logs:/logs
      - ./logging_rsyslog/work:/work
      - ./logging_rsyslog/config:/config
    networks:
        int_net:
            ipv4_address: 10.0.0.42
            
  logging_view:
    build: ./logging_view
    ports:
      - 10410:443
    environment:
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./logging_rsyslog/logs:/logs:ro
    networks:
        int_net:
            ipv4_address: 10.0.0.41

  backup:
    build: ./backup
    ports:
      - 10500:443
    environment:
        SERVICE_NAME: "backup"
        REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./backup/data:/data
    networks:
        int_net:
            ipv4_address: 10.0.0.50    

      
networks:
    int_net:
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
